version: '3'

services:
  sources-db:
    container_name: sources_db
    image: postgres:12
    environment:
    - POSTGRES_DB=sources_api_development
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    ports:
      - 15436:5432
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=32181
      - ZOOKEEPER_SERVER_ID=1

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka
    ports:
      - 9092:9092
      - 29092:29092
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_LISTENERS=DOCKER://${KAFKA_QUEUE_HOST-kafka}:${KAFKA_QUEUE_PORT-29092},LOCALHOST://localhost:${KAFKA_QUEUE_PORT-9092}
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=DOCKER:PLAINTEXT,LOCALHOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=DOCKER
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:32181
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true

  sources-server:
    container_name: sources_server
    build:
      context: .
      dockerfile: Dockerfile
    command: ["run_rails_server"]
    entrypoint: ["entrypoint", "seed_database"]
    environment:
      - ACG_CONFIG=.docker-compose-config.json
      - APP_NAME=sources
      - PATH_PREFIX=api
      - DISABLE_ORG_ADMIN='true'
      - SOURCES_PSKS=${SOURCES_PSK-sources-psk}
      - DISABLE_DATABASE_ENVIRONMENT_CHECK=1
      - ENCRYPTION_KEY=uXfIgSAUq5Oz8goc/zI8HOOo0SI++Sd9mfpgBanYIM4=
      - RAILS_ENV=development
      - SECRET_KEY_BASE=2e13a003477a557ba3fcc6260c2ec69e411238b9b8b530c3c70e71f7cfc905b5f746f5c195a0282342a77ad6acd4e6ef8949106723200a99414fe83393d67344
      - DATABASE_HOST=${DATABASE_HOST-127.0.0.1}
      - DATABASE_PORT=${DATABASE_PORT-5432}
      - QUEUE_HOST=${KAFKA_QUEUE_HOST-kafka}
      - QUEUE_PORT=${KAFKA_QUEUE_PORT-29092}
      - KOKU_SOURCES_API_HOST=sources-client
      - KOKU_SOURCES_API_PORT=4000
    volumes:
      - ./tmp:/opt/sources-api/tmp
      - ./log:/opt/sources-api/log
    #   - ./config:/opt/sources-api/config
    #   - ./db:/opt/sources-api/db
    ports:
      - "3000:3000"
    links:
      - sources-db
    depends_on:
      - sources-db
      - kafka

networks:
 default:
   external:
     name: ${DOCKER_NETWORK_NAME-sources-api_default}
